version: 0.0
os: linux

files:
  - source: /dist/stolt/browser
    destination: /usr/share/nginx/html

permissions:
  - object: /usr/share/nginx/html
    pattern: "**"
    owner: nginx
    group: nginx

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
